### ISSUE TITLE
Splitting the repo into one per plugin

### ISSUE THREAD

**Issue by daniellee** [BTplc/grafana-plugins#1]
Hi,

My name is Daniel Lee and I help with reviewing plugins for Grafana. Really sorry about the delay in reviewing these. I really liked all 4 plugins. I like that each of them does just one thing and does it well. I think they would be fantastic additions to the plugin catalog.

Would you have any objections to breaking this repo up into four repos - one for each plugin? It would make the administration of publishing updates much easier for us. I think it also would make sense for you to keep the issues and PRs for each plugin separate. When these plugins are published, I think you will get a lot of feature requests.

There is already a plugin.json per plugin but they are all missing a version in the info section. I can send PRs for that once the repo is split into 4. The dist directories need to be checked into git too. I know it is a pain to keep them updated but Grafana has no way of compiling plugins on the fly.

### Peak Report

I found one problem in the peak report plugin when running the master branch of Grafana - a breaking change in Lodash 4 (older versions of Grafana use Lodash 2). I'll send a PR to fix that.

Otherwise, I really like the animated gif. Great way to show how to use the plugin. Think I might borrow that idea for some of my plugins!

### Trend Dots

For the thresholds, it wasn't obvious that it expects percentage values. So some sort of visual hint or text would make it much easier. Maybe something in the documentation too.

Otherwise, looks great.

### Alarm Box and Trend Box

Simple plugins and easy to configure. Both would be useful additions to an Ops dashboard.

Thanks for submitting these plugins. Impressive work!

Cheers,
Daniel

**Comment by benthorner** [comment]
Hi Dan. Thanks for the positive feedback! It's nice to be appreciated :-) Regarding your comments:

   - I've created a separate issue to make percentage thresholds more obvious
   - I've created another issue to sort out plugin metadata (version and company logo)
   - We're happy to split the plugins into separate repos and commit the dist directory

We'll close this request when split is complete, and subsequently delete this repo. Sound good?

**Comment by daniellee** [comment]
@benthorner Sounds great!

**Comment by benthorner** [comment]
Hi Dan. This repo has now been cloned and split into 4 repos:

   - https://github.com/BTplc/grafana-peak-report
   - https://github.com/BTplc/grafana-alarm-box
   - https://github.com/BTplc/grafana-trend-dot
   - https://github.com/BTplc/grafana-trend-box

We'll keep this repo until the plugins appear on Grafana.net - I'll do the PR next.

**Comment by daniellee** [comment]
@benthorner Great work!
